### ISSUE TITLE
Scaling problem

### ISSUE THREAD

**Issue by dgruntz** [rolve/gui#1] opened 2021-11-03 19:06 UTC
I am using the library on a Windows machine with a display resolution 3840 x 2400 and the recommended scaling of 250%.
I then executed the following program:

    package ch.fhnw.graphs;
    import gui.Window;
    
    public class Sample {
        public static void main(String[] args) {
            Window window = new Window("Graph", 800, 600);
            window.open();
            window.setColor(255,0,0);
    
            while (window.isOpen()) {
                var x = window.getMouseX();
                var y = window.getMouseY();
                System.out.println(x + "/" + y);
                window.fillCircle(x, y, 10);
                window.refreshAndClear(20);
            }
        }
    }

When the program is started and the cursor is moved, a red circle follows the mouse, and in the console the coordinates of the mouse are printed (in the range (0,0) to (799,599) as expected).

If however the mouse button is pressed (left or right one), then on my machine the rectangle in which the mouse can be moved is restricted to the rectangle (0,0) to (266, 199), i.e. to a third of the defined size (266 == 800/3, 199 == 600/3) in each direction.

On my machine, the screen resulution is 240 and the scaling factor computed in class `Window` with the assignment

    private final int pixelScale = (int) round(getDefaultToolkit().getScreenResolution() / 96.0);

returns the value `pixelScale == 3`, and I think that the reason for the misbehaviour is this `pixelScale` factor, but it seems that it is only applied if the mouse button is pressed.

In addition, it seems that this scaling factor is computed for the primary screen. If I move the application window on a second display which has another scaling factor, then the red circle is no longer below the mouse, i.e. the mouse then moves faster than the red circle.

**Comment by rolve** [comment] 2021-11-05 09:54
Working with multiple displays is a known (remembered) issue. I didn't know it was that bad, though… Indeed, this can probably not be solved using our manual scaling approach.

I checked out @danielkroeni's version. It seems to work “better”, i.e., it does not cause any problems when working with multiple displays. However, there is another (more minor) problem when letting Java do the scaling.

Since the client code draws outside the UI thread, we have our own image buffering going on: The commands draw on a `BufferedImage` that is painted on the `JPanel` later (and possibly multiple times). If we let Java do the scaling, the result will be pixelated for scales greater than 100%, as the buffer has a lower resolution than the window. See the following examples.

125%, Java's scaling:
![java-scaling-125%](https://user-images.githubusercontent.com/2384850/140489942-9ce5153b-ad6a-498f-957e-97a55f3983e6.png)

125%, custom scaling (in this case no scaling happens, as we round down to int):
![manual-scaling-125%](https://user-images.githubusercontent.com/2384850/140489328-da471dfd-8c61-4d6c-8717-a8a32379755d.png)

200%, Java's scaling:
![java-scaling-200%](https://user-images.githubusercontent.com/2384850/140490019-07b6ef46-33fc-4a25-86e4-190d17fe13af.png)

200%, custom scaling:
![manual-scaling-200%](https://user-images.githubusercontent.com/2384850/140489574-29746c6b-4310-4d91-9f00-2bcf44c1b901.png)

To avoid this pixelation, the buffering needs to be implemented differently. I can look into that at some point.

For now, I merged @danielkroeni's changes back into master, bumping the project version along the way. It would be good if both of you could try out this new version `1.2.0-SNAPSHOT` on the machines that had issues and let me know if those are fixed with this version. Of course, this may cause the pixelation issues shown above. One can always go back to using `1.1.0-SNAPSHOT` to get the old behavior.

I'll leave this issue open until we have a solution that scales correctly without pixelation.

**Comment by rolve** [comment] 2021-11-05 13:34
So I couldn't let it go and invested some time to implement a new buffering strategy, see 558ff59c. The pixelation issue above should be solved now. Feel free to try out the new version `1.3.0-SNAPSHOT` and let me know if there are any issues with it.

**Comment by dgruntz** [comment] 2021-11-05 15:38
I just tested the library (version `1.3.0-SNAPSHOT`) with the program shown above in this issue on my laptop where the primary screen is scaled at 250% and the secondary screen is scaled at 125%, and it works fine. It even works if the windows is displayed on both screens at the same time, i.e. half on one screen, half on the other screen; and there are no updating issues when the window is moved from one screen to the other screen.

**Comment by danielkroeni** [comment] 2021-11-05 18:35
Hi @rolve, thank you for your effort. I just tested our OOP1 game using the new version `1.3.0-SNAPSHOT`. Everything works as expected but there seems to be a difference regarding the background color of the window.

With later versions the background of the window was pure white, like the background of our duke picture:
<img width="771" alt="original" src="https://user-images.githubusercontent.com/142282/140560839-b66e83db-ed2e-4f2f-8e50-08df7cbe16c2.png">

With version `1.3.0` it looks more like grey.
<img width="816" alt="1 3 0" src="https://user-images.githubusercontent.com/142282/140560849-eaeb5226-275a-4f1e-bd85-ee7bf7f5f00a.png">

I have attached an [archive](https://github.com/rolve/gui/files/7488211/Export_11_Project_Solution.zip) containing the source code.

**Comment by dgruntz** [comment] 2021-11-06 09:59
I see the same difference regarding the background color in version `1.3.0-SNAPSHOT` compared to versions `1.2.0-SNAPSHOT` and `1.1.0-SNAPSHOT`, even if the screen is not scaled (i.e. with a scaling factor of 100%).

**Comment by rolve** [comment] 2021-11-06 11:21
Thank you so much for testing this. So it looks like the issue is solved. The thing with the background was a small oversight and is fixed now. I didn't create a new version for this; after 24h, when you do `mvn compile` or the equivalent with Gradle, you should get the fixed `1.3.0-SNAPSHOT` version. (You can force the update with `-U` for Maven or `--refresh-dependencies` for Gradle, I think.)

**Closed by rolve** 2021-11-06 11:21 UTC
